# @

###Register
POST http://localhost:5000/app/api/v1/auths/register
Content-Type: application/json

{
    "email": "xxieqmiz@gmail.com",
    "password" : "xxieqmiz",
    "username": "xxieqmiz"
}

# @name login
###Login  
POST http://localhost:5000/app/api/v1/auths/login
Content-Type: application/json

{
    "password" : "minhthien123",
    "username": "minhthien123"
}

###
@authToken = {{login.response.body.token}}
###

POST http://localhost:5000/app/api/v1/auths/login/google
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZnlBY2NvdW50Ijp7ImlkIjoiNjE4ZGNlYThhNjExZjQzNDAyOTYzMjhjIiwiaXNIaWRkZW4iOmZhbHNlLCJ1c2VybmFtZSI6Im1pbmhob2FuZzEiLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM2Njg0MjM5fQ.MD8t_BLLkC4_deWf4Aj8VjRiim1Uaro-CyJHxcr-MEE

