# @

###Register
POST http://localhost:5000/app/api/v1/auths/register
Content-Type: application/json

{
    "email": "nguyenhoang1@gmail.com",
    "password" : "12345",
    "fullname": "Nguyen Anh Tin",
    "username": "minhhoang22",
    "role": "admin",
    "phone": "124567891"
}

# @name login
###Login  
POST http://localhost:5000/app/api/v1/auths/login
Content-Type: application/json

{
    "password" : "12345",
    "username": "minhhoang"
}

###
@authToken = {{login.response.body.token}}
###