
# @name login
###Login  
POST http://localhost:5000/app/api/v1/auths/login
Content-Type: application/json

{
    "password" : "12345",
    "username": "minhhoang"
}

###
@authToken = {{login.response.body.token}}
###

POST http://localhost:5000/app/api/v1/questions/new/61a2476cbede4808fa12367d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZnlBY2NvdW50Ijp7ImlkIjoiNjE4Y2YxODhjNDAzMjZiMjM4ZTlkYTNkIiwidXNlcm5hbWUiOiJtaW5oaG9hbmciLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM3OTgyNTY4fQ.D9r1z7Y4IEdIyIPTPoVzyfsL10_07pShqC9UHeuPAp4

{
    "type": "MULTICHOICE",
    "content": "Số nguyên tố là gì?",
    "embededMedia": "https://data.voh.com.vn/voh/thumbnail/2020/11/27/thumb-so-nguyen-to.jp",
    "answers":["61a247e1bede4808fa123683", "61a247febede4808fa123685","61a24811bede4808fa123687","61a24834bede4808fa123689"],
    "correctAnswers":["D"],
    "maxPoints": 20,
    "status": ""
}
###Get all questions

GET http://localhost:5000/app/api/v1/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZnlBY2NvdW50Ijp7ImlkIjoiNjE4Y2YxODhjNDAzMjZiMjM4ZTlkYTNkIiwiaXNIaWRkZW4iOmZhbHNlLCJ1c2VybmFtZSI6Im1pbmhob2FuZyIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2MzcxNjcwMDZ9.UCEJRMfC8zED2xLmtt-uBZ6kqegXsmgAboF0WPlGIRA


###

GET http://localhost:5000/app/api/v1/questions/618cf9baad4b7a24d85cee72/answers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZnlBY2NvdW50Ijp7ImlkIjoiNjE4ZGNlYThhNjExZjQzNDAyOTYzMjhjIiwiaXNIaWRkZW4iOmZhbHNlLCJ1c2VybmFtZSI6Im1pbmhob2FuZzEiLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM2Njg0MjM5fQ.MD8t_BLLkC4_deWf4Aj8VjRiim1Uaro-CyJHxcr-MEE
