
# @name login
###Login  
POST http://localhost:5000/app/api/v1/auths/login
Content-Type: application/json

{
    "password" : "12345",
    "username": "minhhoang"
}

###
@authToken = {{login.response.body.token}}
###

POST http://localhost:5000/app/api/v1/tests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZnlBY2NvdW50Ijp7ImlkIjoiNjE4Y2YxODhjNDAzMjZiMjM4ZTlkYTNkIiwidXNlcm5hbWUiOiJtaW5oaG9hbmciLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM3OTgyNTY4fQ.D9r1z7Y4IEdIyIPTPoVzyfsL10_07pShqC9UHeuPAp4

{
    "id": "test-1",
    "name": "Science",
    "description": "Bài kiểm tra trắc nghiệm trực tuyến về các chủ đề khoa học tự nhiên, khoa học xã hội.",
    "creator_id": "618d35c07a4165dcf02f7b05",
    "url": "https://www.google.com",
    "status": "DRAFT",
    "startTime": "2021-11-13 00:00",
    "endTime": "2021-11-19 22:00",
    "maxPoints": 70,
    "questions_order": ["question-1", "question-2", "question-3", "question-4", "question-5", "question-6", "question-7"]
}